### ISSUE TITLE
metadata.annotations.* where does the value come from?

### ISSUE THREAD

**Issue by joudaon** [gitops-bridge-dev/gitops-bridge#64]
Hello,

This is not an issue but I a request for information. I have not been able to figure it out by myself.

In the following file for example: argocd/iac/terraform/examples/eks/external-secrets/bootstrap/workloads.yaml

What does {{metadata.annotations.*}} replace? Where does the value come from?

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-example
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: akuity.io/argo-cd-cluster-name
              operator: NotIn
              values: [in-cluster]
  template:
    metadata:
      name: 'external-secrets-example'
    spec:
      project: default
      source:
        repoURL: '{{metadata.annotations.workload_repo_url}}'
        path: '{{metadata.annotations.workload_repo_basepath}}{{metadata.annotations.workload_repo_path}}'
        targetRevision: '{{metadata.annotations.workload_repo_revision}}'
        helm:
          releaseName: 'external-secrets-example'
          values: |
            region: '{{metadata.annotations.aws_region}}'
            externalSecret:
              clusterSecretStore:
                secret: '{{metadata.annotations.workload_sm_secret}}'
              secretStore:
                secret: '{{metadata.annotations.workload_ps_secret}}'
      destination:
        namespace: '{{metadata.annotations.external_secrets_namespace}}'
        name: '{{name}}'
      syncPolicy:
        automated: {}
        retry:
          backoff:
            duration: 1m
          limit: 20
        syncOptions:
          - CreateNamespace=true
```

Thank you.

Regards.
